### ISSUE TITLE
access_token return none

### ISSUE THREAD

**Issue by simonprovost** [FullteaOfEEIC/tinpy2#1]
Hello,

first and foremost, thanks for these tutorials which is really helpful to understand.
So, I've tried your repo and something went wrong.

accesToken.py:

> # 返り値からtokenを取得
> print ("debug : " + str(response.status_code))
> access_token = re.search(r"access_token=([\w\d]+)", response.text).groups()[0]

output : 

> debug : 200
> Traceback (most recent call last):
> File "tinder.py", line 7, in <module>
>    token = getAccessToken(FBemail, FBpass)
>   File "/home/simon/delivery/react/myTest/tinpy2/accessToken.py", line 24, in getAccessToken
>     access_token = re.search(r"access_token=([\w\d]+)", response.text).groups()[0]
>  AttributeError: 'NoneType' object has no attribute 'groups'

Then, I tried to remove .groups... to see the output anad access_token was "none".

Do you have an idea why ?

Thanks,

**Comment by FullteaOfEEIC** [comment]
I'm so sorry for kept you waiting.
I fixed the bug, so please use the latest version.
Thanks.
